### ISSUE TITLE
Stamina needs a rebalance it's far too easy to run out of stamina in combat

### ISSUE THREAD

**Issue by kurozael** [Facepunch/sbox-corewars#16]

**Comment by xezno** [comment]
Thought I'd give my two cents here -- the main problem with stamina is that, if I'm running away from someone and run out of stamina, I'd then need to turn around and fight them. But that isn't possible until stamina recharges to 40%, at which point I'd basically already be dead.. it would be nice if it was possible to still attack at low stamina but do lower damage or something like that.

In addition to that, jumping is a bit painful. With every block being 1m^3 you have to jump in order to get up to a higher block,  so if you make a set of stairs, you end up running out of stamina pretty quickly.. which limits the amount of vertical control you can get, limiting your choices for combat or bed approach.

**Comment by kurozael** [comment]
Yeah I'm gonna make damage scale a bit less with low stamina and severely reduce the jump reduction. Thanks for the feedback :)
